* Geral
** Terminal
#+BEGIN_SRC emacs-lisp
(defvar terminalzito "/bin/zsh")
(defadvice ansi-term (before force-zsh)
  (interactive (list terminalzito)))
(ad-activate 'ansi-term)
#+END_SRC
Definindo o ZSH como interpretador padrão para o ansi-term.
** Toolbar
#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)
#+END_SRC
Desativa toolbar por motivos de ocupa muito espaço e é inútil.
** Menubar
#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
#+END_SRC
Desativa menu bar por também ser inútil
** Scrollbar
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
#+END_SRC
Desativa scroll bar porque não vai ser utilizada.
** Soft-wrap
#+BEGIN_SRC emacs-lisp
(global-visual-line-mode 1)
#+END_SRC
Ativa soft-wrap para melhor visualização do texto.
** Line number mode
#+BEGIN_SRC emacs-lisp
(add-hook 'prog-mode-hook (lambda () (display-line-numbers-mode 1)))
#+END_SRC
Mostra as linhas de texto globalmente.
#+BEGIN_SRC emacs-lisp
(custom-set-variables
    '(tab-width 4))
#+END_SRC
Define tab para 4 espaços.
* Org
** Org Bullets
#+BEGIN_SRC emacs-lisp
(use-package org-bullets
    :ensure t
    :config
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode))))
#+END_SRC
Bullets para deixas o org mode mais bonito.
* Visual
** Tema
#+BEGIN_SRC emacs-lisp
(use-package darkokai-theme
    :ensure t
    :init
    (load-theme 'darkokai t))
#+END_SRC
Seta o tema darkokai como padrão.
** Spaceline
#+BEGIN_SRC emacs-lisp
(use-package spaceline
    :ensure t)
(use-package spaceline-config
    :ensure spaceline
    :config
    (spaceline-emacs-theme))
#+END_SRC
Spaceline com tema emacs padrão.
* Utilidades
** Which key
#+BEGIN_SRC emacs-lisp
(use-package which-key
    :ensure t
    :config
    (which-key-mode 1))
#+END_SRC
Which-key para listar comandos com C-X. 
** Auto Complete
#+BEGIN_SRC emacs-lisp
(use-package auto-complete
    :ensure t
    :init
    (ac-config-default))
#+END_SRC
Pacote de auto-complete
** Dashboard
#+BEGIN_SRC emacs-lisp
(use-package dashboard
    :ensure t
    :config
    (setq dashboard-set-heading-icons t)
    (setq dashboard-set-file-icons t)
	(setq dashboard-startup-banner "~/.emacs.d/img/banner.png")
    :init
    (dashboard-setup-startup-hook))
#+END_SRC
Lindo dashboard 
*** Page break lines
#+BEGIN_SRC emacs-lisp
(use-package page-break-lines
    :ensure t
    :init
    (turn-on-page-break-lines-mode))
#+END_SRC
Substitui símbolo de quebras de linha por uma linha vazia.
*** All the icons
#+BEGIN_SRC emacs-lisp
(use-package all-the-icons
    :ensure t)
#+END_SRC
Autoexplicativo.
** Yasnippet
#+BEGIN_SRC emacs-lisp
(use-package yasnippet
    :ensure t
    :config
    (yas-global-mode 1))
#+END_SRC
Snippet para frameworks.
*** Emacs-Lisp snippet
#+BEGIN_SRC emacs-lisp
(use-package el-autoyas
    :ensure t)
#+END_SRC
*** Javascript e React snippet 
#+BEGIN_SRC emacs-lisp
(use-package js-react-redux-yasnippets
    :ensure t)
#+END_SRC
** Helm
#+BEGIN_SRC emacs-lisp
(use-package helm
    :ensure t
	:config
	(helm-mode 1))
#+END_SRC
Helm para completion.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "M-x") 'helm-M-x)
#+END_SRC
Bindings das keys pro helm.
* Diminish
#+BEGIN_SRC emacs-lisp
(use-package diminish
    :ensure t
	:init
	(diminish 'helm-mode)
	(diminish 'which-key-mode)
	(diminish 'visual-line-mode)
	(diminish 'yas-minor-mode)
	(diminish 'page-break-lines-mode)
	(diminish 'auto-complete-mode))
#+END_SRC
Pacote para esconder os modos da barra
