* Geral
** Terminal
#+BEGIN_SRC emacs-lisp
  (defvar terminalzito "/bin/zsh")
  (defadvice ansi-term (before force-zsh)
    (interactive (list terminalzito)))
  (ad-activate 'ansi-term)


#+END_SRC
Definindo o ZSH como interpretador padrão para o ansi-term.
** Toolbar
#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)
#+END_SRC
Desativa toolbar por motivos de ocupa muito espaço e é inútil.
** Menubar
#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
#+END_SRC
Desativa menu bar por também ser inútil
** Scrollbar
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
#+END_SRC
Desativa scroll bar porque não vai ser utilizada.
** Soft-wrap
#+BEGIN_SRC emacs-lisp
(global-visual-line-mode 1)
#+END_SRC
Ativa soft-wrap para melhor visualização do texto.
** Line number mode
#+BEGIN_SRC emacs-lisp
(add-hook 'prog-mode-hook (lambda () (display-line-numbers-mode 1)))
#+END_SRC
Mostra as linhas de texto para os buffers em prog-mode.
** Tab
#+BEGIN_SRC emacs-lisp
(custom-set-variables
    '(tab-width 4))
#+END_SRC
Define tab para 4 espaços.
** Y-or-n-p
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
Alias para simplificar confirmações.
* Bindings
** Kill buffer and window
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x j") 'kill-buffer-and-window)
#+END_SRC
** Abrir terminal 
#+BEGIN_SRC emacs-lisp
(defun split-and-open-terminal () 
    (interactive)
    (call-interactively 'split-window-right)
    (call-interactively 'other-window)
    (call-interactively 'ansi-term))
(global-set-key (kbd "C-x t") 'split-and-open-terminal)
#+END_SRC
* Org
** Configs
#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook 'org-indent-mode)
#+END_SRC
** Org Bullets
#+BEGIN_SRC emacs-lisp
(use-package org-bullets
    :ensure t
    :config
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode))))
#+END_SRC
Bullets para deixas o org mode mais bonito.
* Visual
** Tema
#+BEGIN_SRC emacs-lisp
(use-package darkokai-theme
    :ensure t
    :init
    (load-theme 'darkokai t))
#+END_SRC
Seta o tema darkokai como padrão.
** Spaceline
#+BEGIN_SRC emacs-lisp
(use-package spaceline
    :ensure t)
(use-package spaceline-config
    :ensure spaceline
    :config
    (spaceline-emacs-theme))
#+END_SRC
Spaceline com tema emacs padrão.
** Dashboard
#+BEGIN_SRC emacs-lisp
(use-package dashboard
    :ensure t
    :config
    (setq dashboard-set-heading-icons t)
    (setq dashboard-set-file-icons t)
	(setq dashboard-startup-banner "~/.emacs.d/img/banner.png")
    :init
    (dashboard-setup-startup-hook))
#+END_SRC
Lindo dashboard 
*** Page break lines
#+BEGIN_SRC emacs-lisp
(use-package page-break-lines
    :ensure t
    :init
    (turn-on-page-break-lines-mode))
#+END_SRC
Substitui símbolo de quebras de linha por uma linha vazia.
*** All the icons
#+BEGIN_SRC emacs-lisp
(use-package all-the-icons
    :ensure t)
#+END_SRC
Autoexplicativo.
* Utilidades
** Which key
#+BEGIN_SRC emacs-lisp
(use-package which-key
    :ensure t
    :config
    (which-key-mode 1))
#+END_SRC
Which-key para listar comandos com C-X. 
** Company
#+BEGIN_SRC emacs-lisp
  (use-package company
      :ensure t
      :config
      (setq company-idle-delay 0)
      (setq company-minimum-prefix-length 3)
      (with-eval-after-load 'company
          (add-hook 'prog-mode-hook 'company-mode)))
#+END_SRC
Pacote de auto-complete

*** Irony
#+BEGIN_SRC emacs-lisp
(use-package company-irony
    :ensure t
    :config
    (add-hook 'c++-mode-hook 'irony-mode)
    (add-hook 'c-mode-hook 'irony-mode))
#+END_SRC
** Yasnippet
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
      :ensure t
      :config
      (use-package yasnippet-snippets
          :ensure t)
      (yas-reload-all)
      (add-hook 'prog-mode-hook #'yas-minor-mode))
#+END_SRC
Snippet para frameworks.
*** Lisp snippet
#+BEGIN_SRC emacs-lisp
(use-package common-lisp-snippets
    :ensure t)
(add-hook 'lisp-mode-hook 'yas-minor-mode)
#+END_SRC
*** Emacs-Lisp snippet
#+BEGIN_SRC emacs-lisp
  (use-package el-autoyas
    :ensure t
    :config
    (add-hook 'org-mode 'el-autoyas-enable))
#+END_SRC
*** Javascript e React snippet 
#+BEGIN_SRC emacs-lisp
(use-package js-react-redux-yasnippets
    :ensure t)
#+END_SRC
** Company+Yasnippet
#+BEGIN_SRC emacs-lisp
(defun check-expansion ()
    (save-excursion
      (if (looking-at "\\_>") t
        (backward-char 1)
        (if (looking-at "\\.") t
          (backward-char 1)
          (if (looking-at "->") t nil)))))

  (defun do-yas-expand ()
    (let ((yas/fallback-behavior 'return-nil))
      (yas/expand)))
#+END_SRC
Funções para integração do company com yasnippet.
** Helm
#+BEGIN_SRC emacs-lisp
(use-package helm
    :ensure t
	:config
	(helm-mode 1))
#+END_SRC
Helm para funções de busca..

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x C-f") 'helm-find-files) ;; helm-find-files
(global-set-key (kbd "M-x") 'helm-M-x)            ;; helm-fuzzy-match
(global-set-key (kbd "M-y") 'helm-show-kill-ring) ;; helm-kill-ring
(global-set-key (kbd "C-x b") 'helm-mini)         ;; helm-mini
#+END_SRC
Bindings das keys pro helm.

** Swipper
#+BEGIN_SRC emacs-lisp
  (use-package swiper
      :ensure t
      :bind ("C-s" . swiper))
#+END_SRC
Pacote para busca mais inteligente.
** Magit
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t)
#+END_SRC
Pacote para integração com o git.
** Flycheck
#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :ensure t
    :init
    (global-flycheck-mode))
#+END_SRC
Detecção e highlightning de erros.

*** C++ 
#+BEGIN_SRC emacs-lisp
  (add-hook 'c++-mode-hook (lambda () (setq flycheck-gcc-language-standard "c++11")))
#+END_SRC
* Diminish
#+BEGIN_SRC emacs-lisp
(use-package diminish
    :ensure t
	:init
	(diminish 'helm-mode)
	(diminish 'which-key-mode)
	(diminish 'visual-line-mode)
	(diminish 'yas-minor-mode)
	(diminish 'page-break-lines-mode)
	(diminish 'company-mode)
  (diminish 'org-indent-mode))
#+END_SRC

Pacote para esconder os modos da
  
